name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "*.md"
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: hynek/setup-cached-uv@4300ec2180bc77d705e626a34e381b81a4772c51 # v2.5.0

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Test
        run: uv run pytest

      - name: Pytest Coverage
        uses: MishaKav/pytest-coverage-comment@e48ae95fa406cefacc7fbdd79949122795569961 # v1.8.0
        if: success()
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          badge-title: Backend Coverage
