name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "*.md"
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: hynek/setup-cached-uv@0b9e52652c2d5d4fb6af4598efa3d14e60e934d1 # v2.4.0

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Test
        run: uv run pytest

      - name: Pytest Coverage
        uses: MishaKav/pytest-coverage-comment@287292879eaaff04116f36d3eb1a670f6e5df1a4 # v1.7.1
        if: success()
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          badge-title: Backend Coverage
